### ISSUE TITLE
USER STORY: Timeline and adding user posts to the timeline

### ISSUE THREAD

**Issue by beckoningstranger** [beckoningstranger/pp4-socialblog#3]
## User Story
  As a **user** I can **create blog posts and find them easily on a timeline that acts as a central hub from where I will access most of the site's content** so that **access all of the content that's relevant to me.**

## Acceptance Criteria

* Acceptance Criteria:
1. Use this wireframe:
![Timeline Page](https://user-images.githubusercontent.com/113430417/215903515-a32e8a2f-cdef-426b-b476-0fabce7257d0.png)
2. Use this color scheme:
![color-scheme](https://user-images.githubusercontent.com/113430417/215903581-480d886f-d41b-4c7b-91f5-332383727a1e.jpg)
Steel pink should be use as color for the cards, but to make it a little easier on the eyes,make it somewhat transparent in front of the dark background. Font should be white.
3. The navbar should an additional item: 'Add a post' that is only visible when users are on their timeline. Clicking this item should take users to '/add-post'.
4. Twitter and Facebook buttons will take users to pages from where they can share the content with only a couple of clicks.
5. Icons below the Post datetime will show number of posted images, comments and likes.
6. The main image visible on all cards should be generated from user uploaded content. Where users don't upload any pictures, use this placeholder:
![default_post](https://user-images.githubusercontent.com/113430417/215904235-afa04453-d3fa-4354-abc1-3cef3e99b5ff.svg)
7. The excerpt shown below the post's picture should be auto-generated from the blog body.
8. For every post, a slug should be auto-generated.
9. Clicking both the post picture and the post title should take users to the post details page for this post: /post/ + the post's slug
  
## Tasks
  
- [ ] Implement a database model that
1. expands Django's user model
2. creates a model for posts
3. creates a model for comments
See attached ERD:
![ERD Chart](https://user-images.githubusercontent.com/113430417/215904791-67314283-3201-4c3c-8eb8-b553c6c72141.jpg)
- [ ] Code the HTML/CSS for the timeline cards
- [ ] Make it so that the timeline automatically shows all posts of the logged in user
